# Generated by Django 2.2.4 on 2019-12-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideagene', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='button_color',
            field=models.CharField(default='#fff', max_length=10),
            preserve_default=False,
        ),
    ]
