# Generated by Django 2.2.4 on 2019-12-17 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideagene', '0002_theme_button_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='button_color',
        ),
    ]
